### ISSUE TITLE
[EmulGL] GL functions to support callbacks as Callable

### ISSUE THREAD

**Issue by valb3r** [jzy3d/jzy3d-api#254]
Functions like `glutCreateMenu` that accepts callback function name as an argument could have overloaded counterparts that accept lambda as an argument.
I.e. instead of 
`public void glutCreateMenu(String func)` one could have `public void glutCreateMenu(Callable func)` - this would increase performance (of course marginally) and code readability due to IDE code navigation support

**Comment by valb3r** [comment]
@martin-pernollet I'm planning to make a contribution with this ticket

**Comment by jzy3d** [comment]
Great!

I haven't used glutCreateMenu up to now. The most important [methods that are used in EmulGL](https://github.com/jzy3d/jzy3d-api/blob/cb3cac253b28fab9c34709abb1fe5d92e84dccbf/jzy3d-emul-gl-awt/src/main/java/org/jzy3d/plot3d/rendering/canvas/EmulGLCanvas.java#L172) and that would deserve such improvements are 

```
public void glutDisplayFunc(String func) 
public void glutReshapeFunc(String func) 
```

Some other could be changed as well for consistency but are not used in Jzy3D : 
```
public void glutKeyboardUpFunc(String func)
public void glutSpecialFunc(String func) 
public void glutSpecialUpFunc(String func) 
public void glutMouseFunc(String func) 
public void glutMotionFunc(String func)
public void glutIdleFunc(String func)
```

I was myself thinking of defining a GLEventListener rather than a Callable. [JOGL define such a listener](https://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/opengl/GLEventListener.html) which is the basis of any JOGL based application. Jzy3D native part implements this listener [here](https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-native-jogl-core/src/main/java/org/jzy3d/plot3d/rendering/view/Renderer3d.java). 

Missing such an interface makes EmulGL bundle canvas code and rendering code inside the same EmulGLCanvas. Having a jGL GLEventListener similar to JOGL would allow EmulGLCanvas to be more consistent with the other native canvases.

**Comment by valb3r** [comment]
@martin-pernollet Implemented Lambda callbacks and Listener-like support as well, kept old string functions too
